config/routes.rb
Teachup::Application.routes.draw do
  
  resources :lectures

  resources :users

  root :to => "pages#home"
  get "pages/home"
  get "pages/home1"
  get "pages/home2"
  get "pages/home3"
  get "pages/home4"
  get "pages/home5"
  get "pages/home6"
  get "pages/home5a"
  get "pages/excel"
  get "pages/maps"
  get "pages/presentation"
  get "pages/proyecto1"
  get "pages/vistaalumno"

  get "pages/ver"
  get "pages/help"
  get "pages/contactus"
  get "pages/video"
    

end

app/models/lecture.rb
class Lecture < ActiveRecord::Base
	

end

app/models/proyecto.rb
class Proyecto < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessible :email, :name
	


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/lectures_controller.rb
class LecturesController < ApplicationController
  # GET /lectures
  # GET /lectures.json
  def index
    @lectures = Lecture.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lectures }
    end
  end

  # GET /lectures/1
  # GET /lectures/1.json
  def show
    @lecture = Lecture.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lecture }
    end
  end

  # GET /lectures/new
  # GET /lectures/new.json
  def new
    @lecture = Lecture.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @lecture }
    end
  end

  # GET /lectures/1/edit
  def edit
    @lecture = Lecture.find(params[:id])
  end

  # POST /lectures
  # POST /lectures.json
  def create
    @lecture = Lecture.new(params[:lecture])

    respond_to do |format|
      if @lecture.save
        format.html { redirect_to @lecture, notice: 'Lecture was successfully created.' }
        format.json { render json: @lecture, status: :created, location: @lecture }
      else
        format.html { render action: "new" }
        format.json { render json: @lecture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lectures/1
  # PUT /lectures/1.json
  def update
    @lecture = Lecture.find(params[:id])

    respond_to do |format|
      if @lecture.update_attributes(params[:lecture])
        format.html { redirect_to @lecture, notice: 'Lecture was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @lecture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lectures/1
  # DELETE /lectures/1.json
  def destroy
    @lecture = Lecture.find(params[:id])
    @lecture.destroy

    respond_to do |format|
      format.html { redirect_to lectures_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
  end

  def home1
  end
  def home2
  end
  def home3
  end
  def home4
  end

  def home6
  end

  def excel
  end

  def maps
  end

  def presentation
  end

  def ver
  end

  def help
  end

  def contactus
  end

  def video
  end

  def proyecto1
  end

  def home5a
  end

end

app/controllers/proyectos_controller.rb
class ProyectosController < ApplicationController
  # GET /proyectos
  # GET /proyectos.json
  def index
    @proyectos = Proyecto.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @proyectos }
    end
  end

  # GET /proyectos/1
  # GET /proyectos/1.json
  def show
    @proyecto = Proyecto.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @proyecto }
    end
  end

  # GET /proyectos/new
  # GET /proyectos/new.json
  def new
    @proyecto = Proyecto.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @proyecto }
    end
  end

  # GET /proyectos/1/edit
  def edit
    @proyecto = Proyecto.find(params[:id])
  end

  # POST /proyectos
  # POST /proyectos.json
  def create
    @proyecto = Proyecto.new(params[:proyecto])

    respond_to do |format|
      if @proyecto.save
        format.html { redirect_to @proyecto, notice: 'Proyecto was successfully created.' }
        format.json { render json: @proyecto, status: :created, location: @proyecto }
      else
        format.html { render action: "new" }
        format.json { render json: @proyecto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /proyectos/1
  # PUT /proyectos/1.json
  def update
    @proyecto = Proyecto.find(params[:id])

    respond_to do |format|
      if @proyecto.update_attributes(params[:proyecto])
        format.html { redirect_to @proyecto, notice: 'Proyecto was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @proyecto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proyectos/1
  # DELETE /proyectos/1.json
  def destroy
    @proyecto = Proyecto.find(params[:id])
    @proyecto.destroy

    respond_to do |format|
      format.html { redirect_to proyectos_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/proyectos_helper.rb
module ProyectosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Teachup
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    

  %body
    
    .row.show-grid 
      .span11.offset1
        .container= yield
    

app/views/lectures/_form.html.haml
= form_for @lecture do |f|
  -if @lecture.errors.any?
    #error_explanation
      %h2= "#{pluralize(@lecture.errors.count, "error")} prohibited this lecture from being saved:"
      %ul
        - @lecture.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/lectures/edit.html.haml
%h1 Editing lecture

= render 'form'

= link_to 'Show', @lecture
\|
= link_to 'Back', lectures_path

app/views/lectures/index.html.haml
%h1 Listing lectures

%table
  %tr
    %th Name
    %th
    %th
    %th

  - @lectures.each do |lecture|
    %tr
      %td= lecture.name
      %td= link_to 'Show', lecture
      %td= link_to 'Edit', edit_lecture_path(lecture)
      %td= link_to 'Destroy', lecture, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Lecture', new_lecture_path

app/views/lectures/new.html.haml
%h1 New lecture

= render 'form'

= link_to 'Back', lectures_path

app/views/lectures/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @lecture.name

= link_to 'Edit', edit_lecture_path(@lecture)
\|
= link_to 'Back', lectures_path

app/views/pages/contactus.html.haml
%h1 Pages#contactus
%p Find me in app/views/pages/contactus.html.erb

app/views/pages/excel.html.haml
%h1 TeachUp
%h3 Spreadsheet Document
%p
%row
  
%p{:style => "float:right ;  margin-top: 370px; margin-right: 30px"}=link_to 'Presentation Ready!', {:controller => "pages", :action => "home2"} , {:class => "btn btn-success"}

%row
  .btn-group
    %a.btn{:href => "#"}
      %i.icon-facetime-video
    %a.btn{:href => "#"}
      %i.icon-pause
    %a.btn{:href => "#"}
      %i.icon-stop
    %span  
      

%span

app/views/pages/help.html.haml
%h1 Pages#help
%p Find me in app/views/pages/help.html.erb

#example
  %p
    A
  %p
    different
  %p
    word
  %p
    appears
  %p
    every
  %p
    one
  %p
    second

app/views/pages/home.html.haml
%header.jumbotron.masthead  
  %h1.first TeachUp!
  %h2.second Just record your next idea...
  %p.download-info
.demo
  %span.draggable
    %a.btn.btn-primary.btn-large{:href => "http://localhost:3000/pages/proyecto1/"} Teacher!
  %span.draggable
    %a.btn.btn-large{:href => "http://localhost:3000/pages/vistaalumno/" }
      Student!
  %span.draggable
    %a.btn.btn-large{:href => "http://localhost:3000/pages/vistaalumno/" }
      Student2!
  .draggable2
    %iframe{:scrolling => "no", :src => "https://www.google.com/fusiontables/embedviz?viz=MAP&q=select+col1+from+1DUdU5aA4_KNtrVQKhX1kJuCiXjL_zwi-UR9mYjI+&h=false&lat=21.19957299537964&lng=176.70654664999995&z=2&t=1&l=col1"}
    = render "partials/handler"
  .draggable2
    %iframe{:scrolling => "no", :src => "https://www.youtube.com/embed/D1R-jKKp3NA?rel=0"}
    = render "partials/handler"
  .draggable2
    %iframe{:src => "http://docs.google.com/viewer?url=http%3A%2F%2Fwww.redsalud.cl%2Fwp-content%2Fuploads%2F2011%2F05%2Fmemoria_2011.pdf&embedded=true"}
    = render "partials/handler"

 
:javascript
  $(function() {
    
    $( ".draggable" ).draggable();
    $( " p" ).disableSelection();
    $( ".draggable2" ).draggable({handle: "a"});
    $( "#droppable" ).droppable({
      drop:function( event, ui ) {
  			$( this )
  				.find( "p" )
  				.html( "Dropped!" );
      }
  	});
  });

app/views/pages/home1.html.haml
%h1 TeachUp!
%h3 Just record your next idea 
%div
  = render 'partials/navelements'

= render 'partials/elementmenu'

%div#container= render 'partials/elementmenu'
= render 'partials/footer'


#container
  #header
    %h1 StarTrackr!
  #content
    %h2
      Welcome!
    %ul#menu
      %li
        %a{:href => "#"} What's new?
        %ul.active
          %li
            %a{:href => "#"} Weekly specials
          %li
            %a{:href => "#"} Last night's pics!
          %li
            %a{:href => "#"} Users' comments
      %li
        %a{:href => "#"} Member extras
        %ul
          %li
            %a{:href => "#"} Premium Celebrities
          %li
            %a{:href => "#"} 24-hour Surveillance
      %li
        %a{:href => "#"} About Us
        %ul
          %li
            %a{:href => "#"} Privacy Statement
          %li
            %a{:href => "#"} Terms and Conditions
          %li
            %a{:href => "#"} Contact Us
    #news
      %h2 Latest News

app/views/pages/home2.html.haml
%h1 TeachUp!
%h3 Just record your next idea 
:css
  .container
    .row
%row{:style => "position:relative"}
%row 
  .sitio{:style => "background: none repeat scroll 0 0 #000000; color: #FFFFFF; font-weight: bold; margin-top: 200px; padding-left: 10px; position:relative; width: 2000px"} Timeline
  %a{:href => "http://localhost:3000/pages/ver"}
    .element1{:style => "background: none repeat scroll 0 0 #999999; color: #000000; font-weight: bold; padding-left: 10px; position:relative; border-style:solid; border-width:medium; border-color:#666666; width:100px; height:60px; -webkit-border-radius: 5px; position:fixed; left:200px ; top:300px"} 
      %img{:src => "http://i2.ytimg.com/vi/uhxtUt_-GyM/default.jpg", :alt => "Thumbnail"}

  %a{:href => "http://localhost:3000/pages/presentation"}
    .element2{:style => "background: none repeat scroll 0 0 #999999; color: #000000; font-weight: bold; padding-left: 10px; position:relative; border-style:solid; border-width:medium; border-color:#666666; width:  100px; height:60px; -webkit-border-radius: 5px; position:fixed; left:400px ; top:300px"} element2

  .element3{:style => "background: none repeat scroll 0 0 #999999; color: #000000; font-weight: bold; padding-left: 10px; position:relative; border-style:solid; border-width:medium; border-color:#666666; width:100px; height:60px; -webkit-border-radius: 5px; position:fixed; left:600px ; top:300px"} element3

  .element4{:style => "background: none repeat scroll 0 0 #999999; color: #000000; font-weight: bold; padding-left: 10px; position:relative; border-style:solid; border-width:medium; border-color:#666666; width:100px; height:60px; -webkit-border-radius: 5px; position:fixed; left:800px ; top:300px"} element4

  .element5{:style => "background: none repeat scroll 0 0 #999999; color: #000000; font-weight: bold; padding-left: 10px; position:relative; border-style:solid; border-width:medium; border-color:#666666; width:100px; height:60px; -webkit-border-radius: 5px; position:fixed; left:1000px ; top:300px"} element5

  .element6{:style => "background: none repeat scroll 0 0 #999999; color: #000000; font-weight: bold; padding-left: 10px; position:relative; border-style:solid; border-width:medium; border-color:#666666; width:100px; height:60px; -webkit-border-radius: 5px; position:fixed; left:1200px ; top:300px"} element6

%span
 
= render 'partials/footer'

app/views/pages/home3.html.haml
%h1 TeachUp!
%h3 Just record your next idea 
:css
  .container
    .row
%row{:style => "position:relative"}
%row 
  .sitio{:style => "background: none repeat scroll 0 0 #000000; color: #FFFFFF; font-weight: bold; margin-top: 200px; padding-left: 10px; position:relative; width: 2000px"} Timeline
  %a{:href => "http://localhost:3000/pages/video"}
    .element1{:style => "background: none repeat scroll 0 0 #999999; color: #000000; font-weight: bold; padding-left: 10px; position:relative; border-style:solid; border-width:medium; border-color:#666666; width:100px; height:60px; -webkit-border-radius: 5px; position:fixed; left:200px ; top:300px"} 
      %img{:src => "http://i2.ytimg.com/vi/uhxtUt_-GyM/default.jpg", :alt => "Thumbnail"}

  .element2{:style => "background: none repeat scroll 0 0 #999999; color: #000000; font-weight: bold; padding-left: 10px; position:relative; border-style:solid; border-width:medium; border-color:#666666; width:100px; height:60px; -webkit-border-radius: 5px; position:fixed; left:400px ; top:300px"} 
    %iframe{:allowfullscreen => "true", :frameborder => "0", :height => "100", :mozallowfullscreen => "true", :src => "https://docs.google.com/presentation/embed?id=1b6okmGFmOC6njQH8LRi1UC2Vo2X2bmuNZjuMhj77FuE&start=false&loop=false&delayms=60000", :webkitallowfullscreen => "true", :width => "100"}

  %a{:href => "https://docs.google.com/spreadsheet/pub?key=0AtJS8s5VDL9cdFBHcHhRa1lyUG1EbTZQOEhnQk1ldUE&output=html"}
    .element3{:style => "background: none repeat scroll 0 0 #999999; color: #000000; font-weight: bold; padding-left: 10px; position:relative; border-style:solid; border-width:medium; border-color:#666666; width:100px; height:60px; -webkit-border-radius: 5px; position:fixed; left:600px ; top:300px"} element3
      

  .element4{:style => "background: none repeat scroll 0 0 #999999; color: #000000; font-weight: bold; padding-left: 10px; position:relative; border-style:solid; border-width:medium; border-color:#666666; width:100px; height:60px; -webkit-border-radius: 5px; position:fixed; left:800px ; top:300px"} element4

  .element5{:style => "background: none repeat scroll 0 0 #999999; color: #000000; font-weight: bold; padding-left: 10px; position:relative; border-style:solid; border-width:medium; border-color:#666666; width:100px; height:60px; -webkit-border-radius: 5px; position:fixed; left:1000px ; top:300px"} element5

  .element6{:style => "background: none repeat scroll 0 0 #999999; color: #000000; font-weight: bold; padding-left: 10px; position:relative; border-style:solid; border-width:medium; border-color:#666666; width:100px; height:60px; -webkit-border-radius: 5px; position:fixed; left:1200px ; top:300px"} element6
%span
 
= render 'partials/footer'

app/views/pages/home4.html.haml
%h1 TeachUp!
%h3 Just record your next idea 
:css
  .container
    .row
%row{:style => "position:relative"}
%row 
  .sitio{:style => "background: none repeat scroll 0 0 #000000; color: #FFFFFF; font-weight: bold; margin-top: 200px; padding-left: 10px; position:relative; width: 2000px"} Timeline
  %a{:href => "http://localhost:3000/pages/video"}
    .element1{:style => "background: none repeat scroll 0 0 #999999; color: #000000; font-weight: bold; padding-left: 10px; position:relative; border-style:solid; border-width:medium; border-color:#666666; width:100px; height:60px; -webkit-border-radius: 5px; position:fixed; left:200px ; top:300px"} 
      %img{:src => "http://i2.ytimg.com/vi/uhxtUt_-GyM/default.jpg", :alt => "Thumbnail"}

  .element2{:style => "background: none repeat scroll 0 0 #999999; color: #000000; font-weight: bold; padding-left: 10px; position:relative; border-style:solid; border-width:medium; border-color:#666666; width:100px; height:60px; -webkit-border-radius: 5px; position:fixed; left:400px ; top:300px"} 
    %iframe{:allowfullscreen => "true", :frameborder => "0", :height => "100", :mozallowfullscreen => "true", :src => "https://docs.google.com/presentation/embed?id=1b6okmGFmOC6njQH8LRi1UC2Vo2X2bmuNZjuMhj77FuE&start=false&loop=false&delayms=60000", :webkitallowfullscreen => "true", :width => "100"}

  .element3{:style => "background: none repeat scroll 0 0 #999999; color: #000000; font-weight: bold; padding-left: 10px; position:relative; border-style:solid; border-width:medium; border-color:#666666; width:100px; height:60px; -webkit-border-radius: 5px; position:fixed; left:600px ; top:300px"} 
    %img{:src => "https://encrypted-tbn1.google.com/images?q=tbn:ANd9GcSdv4pIJ1XwtdDuACno9zf5BmYaqFfguvOWbpbWnlQHPduUyavxzw", :alt => "Thumbnail"} 
  %a{:href => "https://www.google.com/fusiontables/DataSource?snapid=S463783ysHF"}
    .element4{:style => "background: none repeat scroll 0 0 #999999; color: #000000; font-weight: bold; padding-left: 10px; position:relative; border-style:solid; border-width:medium; border-color:#666666; width:100px; height:60px; -webkit-border-radius: 5px; position:fixed; left:800px ; top:300px"} element4

  .element5{:style => "background: none repeat scroll 0 0 #999999; color: #000000; font-weight: bold; padding-left: 10px; position:relative; border-style:solid; border-width:medium; border-color:#666666; width:100px; height:60px; -webkit-border-radius: 5px; position:fixed; left:1000px ; top:300px"} element5

  .element6{:style => "background: none repeat scroll 0 0 #999999; color: #000000; font-weight: bold; padding-left: 10px; position:relative; border-style:solid; border-width:medium; border-color:#666666; width:100px; height:60px; -webkit-border-radius: 5px; position:fixed; left:1200px ; top:300px"} element6
%span


= render 'partials/footer'

app/views/pages/home5.html.haml
%h1 TeachUp!
%h3 Just record your next idea 
:css
  .container
    .row
%row{:style => "position:relative"}
%row 
  .sitio{:style => "background: none repeat scroll 0 0 #000000; color: #FFFFFF; font-weight: bold; margin-top: 200px; padding-left: 10px; position:relative; width: 2000px"} Timeline
  %a{:href => "http://localhost:3000/pages/video"}
    .element1{:style => "background: none repeat scroll 0 0 #999999; color: #000000; font-weight: bold; padding-left: 10px; position:relative; border-style:solid; border-width:medium; border-color:#666666; width:100px; height:60px; -webkit-border-radius: 5px; position:fixed; left:200px ; top:300px"} 
      %img{:src => "http://i2.ytimg.com/vi/uhxtUt_-GyM/default.jpg", :alt => "Thumbnail"}

  .element2{:style => "background: none repeat scroll 0 0 #999999; color: #000000; font-weight: bold; padding-left: 10px; position:relative; border-style:solid; border-width:medium; border-color:#666666; width:100px; height:60px; -webkit-border-radius: 5px; position:fixed; left:400px ; top:300px"} 
    %iframe{:allowfullscreen => "true", :frameborder => "0", :height => "100", :mozallowfullscreen => "true", :src => "https://docs.google.com/presentation/embed?id=1b6okmGFmOC6njQH8LRi1UC2Vo2X2bmuNZjuMhj77FuE&start=false&loop=false&delayms=60000", :webkitallowfullscreen => "true", :width => "100"}

  .element3{:style => "background: none repeat scroll 0 0 #999999; color: #000000; font-weight: bold; padding-left: 10px; position:relative; border-style:solid; border-width:medium; border-color:#666666; width:100px; height:60px; -webkit-border-radius: 5px; position:fixed; left:600px ; top:300px"} 
    %img{:src => "https://encrypted-tbn1.google.com/images?q=tbn:ANd9GcSdv4pIJ1XwtdDuACno9zf5BmYaqFfguvOWbpbWnlQHPduUyavxzw", :alt => "Thumbnail"} 
  %a{:href => "https://www.google.com/fusiontables/DataSource?snapid=S463783ysHF"}
    .element4{:style => "background: none repeat scroll 0 0 #999999; color: #000000; font-weight: bold; padding-left: 10px; position:relative; border-style:solid; border-width:medium; border-color:#666666; width:100px; height:60px; -webkit-border-radius: 5px; position:fixed; left:800px ; top:300px"} 
      %img{:src => "https://encrypted-tbn0.google.com/images?q=tbn:ANd9GcSsLkmsSJ0qoidauKttKeTiwaXM5BNi5TJ9TGkSnSKwyejSP4Xn"} 

  .element5{:style => "background: none repeat scroll 0 0 #999999; color: #000000; font-weight: bold; padding-left: 10px; position:relative; border-style:solid; border-width:medium; border-color:#666666; width:100px; height:60px; -webkit-border-radius: 5px; position:fixed; left:1000px ; top:300px"} element5

  .element6{:style => "background: none repeat scroll 0 0 #999999; color: #000000; font-weight: bold; padding-left: 10px; position:relative; border-style:solid; border-width:medium; border-color:#666666; width:100px; height:60px; -webkit-border-radius: 5px; position:fixed; left:1200px ; top:300px"} element6
%span


= render 'partials/footer'

app/views/pages/home5a.html.haml
%h1 TeachUp!
%h3 Just record your next idea 
:css
  .container
    .row
%row{:style => "position:relative"}
%row 
  .sitio{:style => "background: none repeat scroll 0 0 #000000; color: #FFFFFF; font-weight: bold; margin-top: 200px; padding-left: 10px; position:relative; width: 800px"} Timeline
  %a{:href => "http://localhost:3000/pages/video"}
    .element1{:style => "background: none repeat scroll 0 0 #999999; color: #000000; font-weight: bold; padding-left: 10px; position:relative; border-style:solid; border-width:medium; border-color:#666666; width:100px; height:60px; -webkit-border-radius: 5px; position:fixed; left:200px ; top:300px"} 
      %img{:src => "http://i2.ytimg.com/vi/uhxtUt_-GyM/default.jpg", :alt => "Thumbnail"}

  .element2{:style => "background: none repeat scroll 0 0 #999999; color: #000000; font-weight: bold; padding-left: 10px; position:relative; border-style:solid; border-width:medium; border-color:#666666; width:100px; height:60px; -webkit-border-radius: 5px; position:fixed; left:400px ; top:300px"} 
    %iframe{:allowfullscreen => "true", :frameborder => "0", :height => "100", :mozallowfullscreen => "true", :src => "https://docs.google.com/presentation/embed?id=1b6okmGFmOC6njQH8LRi1UC2Vo2X2bmuNZjuMhj77FuE&start=false&loop=false&delayms=60000", :webkitallowfullscreen => "true", :width => "100"}

  .element3{:style => "background: none repeat scroll 0 0 #999999; color: #000000; font-weight: bold; padding-left: 10px; position:relative; border-style:solid; border-width:medium; border-color:#666666; width:100px; height:60px; -webkit-border-radius: 5px; position:fixed; left:600px ; top:300px"} 
    %img{:src => "https://encrypted-tbn1.google.com/images?q=tbn:ANd9GcSdv4pIJ1XwtdDuACno9zf5BmYaqFfguvOWbpbWnlQHPduUyavxzw", :alt => "Thumbnail"} 
  %a{:href => "https://www.google.com/fusiontables/DataSource?snapid=S463783ysHF"}
    .element4{:style => "background: none repeat scroll 0 0 #999999; color: #000000; font-weight: bold; padding-left: 10px; position:relative; border-style:solid; border-width:medium; border-color:#666666; width:100px; height:60px; -webkit-border-radius: 5px; position:fixed; left:800px ; top:300px"} 
      %img{:src => "https://encrypted-tbn0.google.com/images?q=tbn:ANd9GcSsLkmsSJ0qoidauKttKeTiwaXM5BNi5TJ9TGkSnSKwyejSP4Xn"} 
%span


= render 'partials/footer'

app/views/partials/_footer.html.haml
%footer  
  %h4 Ready? Share it!
  %button.btn.btn-info{:href =>"#"}  Facebook
  %button.btn.btn-warning{:href =>"#"}  Twitter
  %p=link_to 'My TeachUp!', {:controller => "pages", :action => "proyecto1"} , {:class => "btn btn-success", :style => "margin-top: 5px;"}

app/views/proyectos/index.html.haml
%h1 Listing proyectos

%table
  %tr
    %th
    %th
    %th

  - @proyectos.each do |proyecto|
    %tr
      %td= link_to 'Show', proyecto
      %td= link_to 'Edit', edit_proyecto_path(proyecto)
      %td= link_to 'Destroy', proyecto, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Proyecto', new_proyecto_path

app/views/proyectos/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_proyecto_path(@proyecto)
\|
= link_to 'Back', proyectos_path

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
%h1 Listing users

%table
  %tr
    %th Name
    %th Email
    %th
    %th
    %th

  - @users.each do |user|
    %tr
      %td= user.name
      %td= user.email
      %td= link_to 'Show', user
      %td= link_to 'Edit', edit_user_path(user)
      %td= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New User', new_user_path

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @user.name
%p
  %b Email:
  = @user.email

= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path